# Site settings
title: Hagen Fritz
email: hagenfritz@utexas.edu
description: >- # this means to ignore newlines until "baseurl:"
  Thank you for visiting my site - feel free to poke around. If you have any questions,
  don't hesitate to reach out!
baseurl: / # the subpath of your site, e.g. /blog
url: https://hagenfritz.github.io # the base hostname & protocol for your site, e.g. http://example.com

# Fields that minima uses that are not default
author: Hagen Fritz
# minima settings
minima:
  date_format: "%b %-d, %Y"
  skin: dark
  social_links:
    linkedin: hagenearlfritz
    instagram: itshagennothagen
    twitter: TheHage
    github:  HagenFritz
# Custom Fields
# title-logo: to create a title logo; 50 px height is ideal
title-logo: /images/title-image.png

# Build settings
# Using regular theme:
# theme: minima
plugins:
  - jekyll-feed

# Taxonomies
taxonomies:
  category: categories
  tag: tags

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
